apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels: { app: users }
    spec:
      containers:
      - name: users
        image: users:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGO_URI
            value: mongodb://mongo:27017/usersdb
        ports:
          - containerPort: 3000
